# Configuration GitLab pour l'environnement de développement
gitlab:
  api_url: https://gitlab.example.com/api/v4
  private_token: your_private_token
  # Nombre de secondes avant timeout de la requête
  timeout: 30
  # Nombre maximal de tentatives en cas d'échec
  max_retries: 3
  # Délai entre les tentatives (en secondes)
  retry_delay: 5
  # Nombre d'éléments par page pour les requêtes paginées
  items_per_page: 100

# Configuration SonarQube pour l'environnement de développement
sonarqube:
  api_url: https://sonarqube.example.com/api
  token: your_sonarqube_token
  # Alternative au token (non recommandée)
  username: ""
  password: ""
  # Nombre de secondes avant timeout de la requête
  timeout: 30
  # Nombre maximal de tentatives en cas d'échec
  max_retries: 3
